### ISSUE TITLE
Release this composer.json package on packagist

### ISSUE THREAD

**Issue by ThaDafinser** [woothee/woothee#19]
There is currently no packages available:
https://packagist.org/packages/woothee/

**Comment by yuya-takeyama** [comment]
@ThaDafinser 
Hi, you mean YAML datasets?

**Comment by yuya-takeyama** [comment]
@ThaDafinser 
I've setup it now!
https://packagist.org/packages/woothee/woothee-testset

Could you please check it and close this issue if you are happy with it?

**Comment by ThaDafinser** [comment]
Cool thing @yuya-takeyama 

I will include it soon in the comparison!

**Comment by ThaDafinser** [comment]
@yuya-takeyama i added them now. Thank you!

You can view the results here: http://thadafinser.github.io/UserAgentParserComparison/results/index.html
