### ISSUE TITLE
Wrong browser name and version (used as Hive UDF)

### ISSUE THREAD

**Issue by ssmane3** [woothee/woothee#23]
user-agent string - 
```
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
```

UDF Output (wrong)- 
```
name = Edge
version = 13.10586
```

expected output -
```
name = Chrome
version = 46.0.2486.0
```

**Comment by ThaDafinser** [comment]
@ssmane3 are you sure this should be Chrome?

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F46.0.2486.0+Safari%2F537.36+Edge%2F13.10586

**Comment by ssmane3** [comment]
I checked online and As per wurlf... UDF output is correct ( i.e. name = Edge and version = 13.10586 ).
As per UA detector it is giving chrome. UA detector library is not updated since 2 years. This may be cause wrong result.

thanks

**Comment by tagomoris** [comment]
That UA is of Edge.

**Comment by ssmane3** [comment]
user-agent string - 
`Mozilla/5.0 (Linux; U; Android 6.0; en-US; XT1068 Build/MPB24.65-34) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.8.730 U3/0.8.0 Mobile Safari/534.30`

UDF output - 
`{"version":"4.0","category":"smartphone","name":"Safari","os":"Android","vendor":"Apple","os_version":"6.0"}`

Online parsers and Wurlf output - 
[(http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+U%3B+Android+6.0%3B+en-US%3B+XT1068+Build%2FMPB24.65-34%29+AppleWebKit%2F534.30+%28KHTML%2C+like+Gecko%29+Version%2F4.0+UCBrowser%2F10.8.8.730+U3%2F0.8.0+Mobile+Safari%2F534.30)]

Please let me know what to consider ?
