### ISSUE TITLE
Test - browser name and version (Hive UDF)

### ISSUE THREAD

**Issue by ssmane3** [woothee/woothee#24]
user-agent string - 
`Mozilla/5.0 (Linux; U; Android 6.0; en-US; XT1068 Build/MPB24.65-34) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.8.730 U3/0.8.0 Mobile Safari/534.30`

UDF output - 
`{"version":"4.0","category":"smartphone","name":"Safari","os":"Android","vendor":"Apple","os_version":"6.0"}`

Online parsers and Wurlf output - 
[(http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+U%3B+Android+6.0%3B+en-US%3B+XT1068+Build%2FMPB24.65-34%29+AppleWebKit%2F534.30+%28KHTML%2C+like+Gecko%29+Version%2F4.0+UCBrowser%2F10.8.8.730+U3%2F0.8.0+Mobile+Safari%2F534.30)]

Please let me know what to consider ?

**Comment by tagomoris** [comment]
"UC Browser" is something new for woothee.
I don't well about Android eco system... is it enough major one (to add testsets)?

**Comment by ssmane3** [comment]
We need to measure user behaviour based on what browser they used. UC browser is one them and it is having enough traffic that can be comparable.

**Comment by tagomoris** [comment]
Okay. Please send us a pull-request for testset. 

iPhone$B$+$iAw?.(B

2016/04/27 22:58$B!"(Bssmane3 <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by ssmane3** [comment]
Yeah sure. Thanks..

**Comment by tagomoris** [comment]
It looks outdated. Feel free to reopen if it's still valid.
