### ISSUE TITLE
A bug with Linux user_agent and some new OSs to consider added

### ISSUE THREAD

**Issue by hohsiangwu** [woothee/woothee#25]
I found these samples using hive udf, and confirmed that it is reproducible in python client.
#### Bug with Linux user_agent

``` python
In [3]: woothee.parse("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Web Preview) Chrome/27.0.1453 Safari/537.36")
Out[3]:
{'category': 'crawler',
 'name': 'Google Web Preview',
 'os': 'UNKNOWN',
 'os_version': 'UNKNOWN',
 'vendor': 'UNKNOWN',
 'version': 'UNKNOWN'}

In [4]: woothee.parse("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453 Safari/537.36")
Out[4]:
{'category': 'pc',
 'name': 'Chrome',
 'os': 'Linux',
 'os_version': 'UNKNOWN',
 'vendor': 'Google',
 'version': '27.0.1453'}
```
#### New OSs

OpenBSD

``` python
In [5]: woothee.parse("Mozilla/5.0 (X11; OpenBSD amd64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36")
Out[5]:
{'category': 'UNKNOWN',
 'name': 'Chrome',
 'os': 'UNKNOWN',
 'os_version': 'UNKNOWN',
 'vendor': 'Google',
 'version': '44.0.2403.125'}
```

For [Opera Mini](http://www.opera.com/mobile/mini), seems it has both Android and iOS version, it will be more difficult to find out from the user_agent.

``` python
In [2]: woothee.parse("Opera/9.80 (SpreadTrum; Opera Mini/4.4.31492/37.8104; U; en) Presto/2.12.423 Version/12.16")
Out[2]:
{'category': 'UNKNOWN',
 'name': 'Opera',
 'os': 'UNKNOWN',
 'os_version': 'UNKNOWN',
 'vendor': 'Opera',
 'version': '12.16'}
```

**Comment by tagomoris** [comment]
"Google Web Previe" looks a kind of crawler, which collect data to show preview pages for Google users. So it's not bug, I think.
"OpenBSD" and something under Opera Mini are ... This library does focus on major user agents, to reduce maintenance cost. Are these good to support?

**Comment by hohsiangwu** [comment]
Thank you for replying this quick!

Even if "Google Web Preview" is a crawler, does it still make sense to fill in the OS field with Linux?

Since BSD is supported, maybe it's worth adding OpenBSD into the family?

Opera Mini is more difficult to determine OS only based on user_agent I think.

**Comment by tagomoris** [comment]
In many cases, crawlers leave huge amount of logs, and parsing OSs for such agents consumes CPU times. I think there's no worth to parse it...
Opera Mini's user-agent looks not to have information about OSs, so I think this library should NOT support it (because it is "parser").

About OpenBSD, it's correct that FreeBSD is supported so OpenBSD should be supported too. Please send us pull-requests :)
