### ISSUE TITLE
IE 6 , 10 are not parsed properly.

### ISSUE THREAD

**Issue by omkumar87** [woothee/woothee#34]
Mozilla/5.0 (compatible; WOW64; MSIE 10.0; Windows NT 6.2)
Mozilla/4.0 (Windows; MSIE 6.0; Windows NT 5.2)
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)

These user agents are not parsed properly.
They are giving browser names as unknown
 Please check the same

**Comment by tagomoris** [comment]
This looks too old and outdated. Feel free to reopen if it's still valid.
