### ISSUE TITLE
SP Type Googlebot recognize issue

### ISSUE THREAD

**Issue by hikariru** [woothee/woothee#49]
As far as I can see, this library doesn't follow the update of Smart Phone type Googlebot UA on Apr. 2018.

former UA: something like `Googlebot-Mobile` (Couldn't find full UA string)
current:
```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
```

see also: https://support.google.com/webmasters/answer/1061943?hl=en

Please could you guys take care of the update?

Thanks.

**Comment by tagomoris** [comment]
According to the result of demo site, "Current" one is parsed as Googlebot. : http://woothee.github.io/
![screen shot 2018-09-21 at 17 37 21](https://user-images.githubusercontent.com/230654/45870078-0d0d9100-bdc5-11e8-8e39-509ecfb415de.png)

**Comment by hikariru** [comment]
Sorry for sharing abstract info with you.
Just wanted a way to check SP type Googlebot, but I found a solution for my usecase somehow.

Thanks for giving me your time :)
