### ISSUE TITLE
Cannot detect `SamsungBrowser`

### ISSUE THREAD

**Issue by Kounotori-ssbm** [woothee/woothee#56]
UserAgent: `Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-G925F Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36`

Result:
![image](https://user-images.githubusercontent.com/19996147/91833958-5db0e880-ec82-11ea-8a8f-17bd4289fb36.png)

I wish this browser's name were detected as "`SamsungBrowser`" or something...

`SamsungBrowser` (Samsung Internet Browser) is the 3rd on "[Mobile Browser Market Share Worldwide](https://gs.statcounter.com/browser-market-share/mobile/worldwide)", so I need detecting this browser.
Could you solve this issue?

**Comment by tagomoris** [comment]
I'm positive to add its support.
@Kounotori-ssbm Could you create the pull-req to add it?

**Comment by Kounotori-ssbm** [comment]
I've created pull-req!
