### ISSUE TITLE
HeadlessChrome is not being recognized as a crawler

### ISSUE THREAD

**Issue by akicho8** [woothee/woothee#75]
Could you please register the UserAgent specified below as a crawler, as its category was identified as "pc" upon checking with http://woothee.github.io/

UserAgent:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/99.0.4844.51 Safari/537.36`

Thank you for your consideration.

**Comment by tagomoris** [comment]
Is that really expected to be a crawler? I guess:

* In macro view: no major crawler fleet using HeadlessChrome as-is
  * So the percentage of pc/crawler doesn't change if we move HeadlessChrome from PC to crawler
* In micro view: HeadlessChrome user wants to behave just like PC
  * If the server returns contents for crawlers, it should be against the client's expectation (I know, changing behavior by user-agent is a bad manner!)

Any thoughts?

**Comment by akicho8** [comment]
It is generally true that content should not be differentiated based on whether it is accessed via HeadlessChrome or not. However, on the website that I operate, there were 6,184 unreasonable and continuous accesses from HeadlessChrome within a span of approximately two hours. It requires allocating resources to handle such accesses, causing inconvenience for regular users and even causing pseudo-DOS attacks on a separate service that is used as a WEB API. Consequently, it would be appreciated if HeadlessChrome is recognized as a crawler. Nevertheless, as it is just a matter of self-determination, it is also acceptable to close this issue.
